longhorn:
  persistence:
    defaultClassReplicaCount: 1

ingress:
  enabled: true
  ingressClassName: nginx
  host: longhorn.checinski.xyz
  tls: true
  secureBackends: true
  tlsSecret: longhorn-checinski-xyz-tls
  path: /
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/auth-url: "https://auth.checinski.xyz/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: https://auth.checinski.xyz/oauth2/start
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: longhorn
    gethomepage.dev/group: cluster
  secrets: