---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: n8n-volsync
  namespace: n8n
spec:
  sourcePVC: n8n-data
  trigger:
    schedule: "0 6 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: restic-config
    cacheCapacity: 2Gi
    volumeSnapshotClassName: csi-rbdplugin-snapclass
    storageClassName: longhorn
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    retain:
      daily: 10
      within: 3d