apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  type: ClusterIP
  selector:
    app: mosquitto
  ports:
    - port: 1883
      targetPort: default
      protocol: TCP
      name: default
    - port: 9001
      targetPort: websocket
      protocol: TCP
      name: websocket