homepage:
  enableRbac: true
  serviceAccount:
    create: true
  config:
    bookmarks:
    #   - Developer:
    #       - Github:
    #           - abbr: GH
    #             href: https://github.com/
    services:
    #   - My First Group:
    #       - My First Service:
    #           href: http://localhost/
    #           description: Homepage is awesome
    widgets:
      - resources:
          backend: kubernetes
          expanded: true
          cpu: true
          memory: true
      - kubernetes:
          cluster:
            show: true
            cpu: true
            memory: true
            showLabel: true
            label: "cluster"
          nodes:
            show: true
            cpu: true
            memory: true
            showLabel: true
      - longhorn:
          expanded: true
          total: true
          labels: true
          nodes: true
    kubernetes:
      mode: cluster
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: 'true'
      hosts:
        - host: homepage.checinski.xyz
          paths:
          - path: /
            pathType: Prefix
      tls:
        - hosts:
          - "homepage.checinski.xyz"
          secretName: homepage-checinski-xyz-tls