apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-forward-auth
  labels:
    app: traefik-forward-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-forward-auth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: traefik-forward-auth
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: thomseddon/traefik-forward-auth:2
        name: traefik-forward-auth
        ports:
        - containerPort: 4181
          protocol: TCP
        env:
        - name: CONFIG
          value: "/config"
        - name: DOMAIN
          value: "checinski.xyz"
        # INSECURE_COOKIE is required if not using a https entrypoint
        # - name: INSECURE_COOKIE
        #   value: "true"
        # Remove COOKIE_DOMAIN if not using auth host mode
        - name: COOKIE_DOMAIN
          value: "checinski.xyz"
        - name: AUTH_HOST
          value: "auth.checinski.xyz"
        - name: LOG_LEVEL
          value: "debug"
        - name: PROVIDERS_GENERIC_OAUTH_SCOPE
          value: user:email
        - name: PROVIDERS_GENERIC_OAUTH_AUTH_URL
          value: "https://github.com/login/oauth/authorize"
        - name: PROVIDERS_GENERIC_OAUTH_TOKEN_URL
          value: "https://github.com/login/oauth/access_token"
        - name: PROVIDERS_GENERIC_OAUTH_USER_URL
          value: "https://api.github.com/user"
        - name: PROVIDERS_GENERIC_OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-secrets
              key: client-id
        - name: PROVIDERS_GENERIC_OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-secrets
              key: client-secret
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-secrets
              key: secret
        volumeMounts:
        - name: configs
          mountPath: /config
          subPath: traefik-forward-auth.ini

      volumes:
      - name: configs
        configMap:
          name: configs
      - name: traefik-forward-auth-secrets
        secret:
          secretName: traefik-forward-auth-secrets