apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik-forward-auth
commonLabels:
  app: traefik-forward-auth

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- middleware.yaml

#
# Configs
#
configMapGenerator:
- name: configs
  files:
    - configs/traefik-forward-auth.ini