apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - overlays/ingress.yaml

## changes to config maps
patchesStrategicMerge:
  - overlays/argocd-cmd-params-cm-patch.yml

namespace: argocd