unifi:
  service:
    main:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.201

  ingress:
    main:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        cert-manager.io/cluster-issuer: letsencrypt
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: 'true'

    portal:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        cert-manager.io/cluster-issuer: letsencrypt
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: 'true'
        flame.pawelmalak/type: application
        flame.pawelmalak/name: unifi
        flame.pawelmalak/url: https://unifi.checinski.xyz

      ingressClassName: "nginx"

      hosts:
        - host: unifi.checinski.xyz
          http:
            paths:
              -
                path: /
                pathType: Prefix
                service:
                  name: main
                  port: portal-https

  persistence:
    config:
      enabled: true
      type: pvc
      existingClaim: unifi