unifi:
  service:
    main:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.201

  ingress:
    main:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        cert-manager.io/cluster-issuer: letsencrypt
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: 'true'
        gethomepage.dev/name: unifi
        gethomepage.dev/group: network
        gethomepage.dev/enabled: "true"

      ingressClassName: "nginx"

      hosts:
        - host: unifi.checinski.xyz
          http:
            paths:
              - path: /
                pathType: Prefix
      tls:
        - hosts:
            - "unifi.checinski.xyz"
          secretName: unifi-checinski-xyz-tls

  persistence:
    config:
      enabled: true
      type: pvc
      existingClaim: unifi