apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-origin-ca-issuer
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: cloudflare/origin-ca-issuer
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  destination:
    namespace: cert-manager
    server: "https://kubernetes.default.svc"
  source:
    repoURL: 'https://github.com/michalchecinski/k8s-gitops.git'
    path: cloudflare-origin-ca-issuer
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true