apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: k8s.gcr.io/external-dns/external-dns
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  destination:
    namespace: external-dns
    server: "https://kubernetes.default.svc"
  source:
    repoURL: 'https://github.com/michalchecinski/k8s-gitops.git'
    path: external-dns
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true