apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/michalchecinski/k8s-gitops.git'
      path: home-assistant
      targetRevision: master
    - chart: home-assistant
      repoURL: https://k8s-at-home.com/charts/
      targetRevision: 13.4.2
      helm:
        releaseName: home-assistant
        values: |
          image:
            repository: homeassistant/home-assistant
            tag: 2023.3.1
          env:
            TZ: "Europe/Warsaw"
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          service:
            main:
              type: ClusterIP
          ingress:
            main:
              enabled: true
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt
                kubernetes.io/ingress.class: nginx
                kubernetes.io/tls-acme: 'true'
                flame.pawelmalak/type: application
                flame.pawelmalak/name: home-assistant
                flame.pawelmalak/url: https://hass.checinski.xyz
              hosts:
              - host: hass.checinski.xyz
                paths:
                - path: /
                  pathType: Prefix
              tls:
              - hosts:
                - "hass.checinski.xyz"
                secretName: hass-checinski-xyz-tls
          prometheus:
            serviceMonitor:
              enabled: false
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: true
          persistence:
            config:
              enabled: true
              storageClass: "longhorn"
              accessMode: ReadWriteOnce
              size: "5Gi"
          addons:
            codeserver:
              enabled: true
              image:
                repository: codercom/code-server
                tag: 4.7.1
              workingDir: "/config"
              args:
                - --user-data-dir
                - "/config/.vscode"
                - --auth
                - "none"
              ingress:
                enabled: true
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt
                  kubernetes.io/ingress.class: nginx
                  kubernetes.io/tls-acme: 'true'
                  nginx.ingress.kubernetes.io/auth-url: "https://auth.checinski.xyz/oauth2/auth"
                  nginx.ingress.kubernetes.io/auth-signin: https://auth.checinski.xyz/oauth2/start
                  flame.pawelmalak/type: application
                  flame.pawelmalak/name: hass-vscode
                  flame.pawelmalak/url: https://hass-vscode.checinski.xyz
                hosts:
                - host: hass-vscode.checinski.xyz
                  paths:
                  - path: /
                    pathType: Prefix
                tls:
                - hosts:
                  - hass-vscode.checinski.xyz
                  secretName: hass-vscode-checinski-xyz-tls
              volumeMounts:
              - name: config
                mountPath: /config
          postgresql:
            enabled: true
            image:
              repository: postgres
              tag: '14.1'
            auth:
              enablePostgresUser: false
              username: home-assistant
              database: home-assistant
            postgresqlDataDir: "/data/pgdata"
            shmVolume:
              enabled: false
            volumePermissions:
              enabled: false
            primary:
              persistence:
                enabled: true
                storageClass: "longhorn"
                size: 1Gi
                mountPath: "/data/"

  destination:
    server: "https://kubernetes.default.svc"
    namespace: hass
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
