apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: velero
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    chart: velero
    repoURL: https://github.com/vmware-tanzu/velero
    targetRevision: 5.0.2

  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true