apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx2
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.7.0
    helm:
      releaseName: nginx
      values: |
        controller:
          replicaCount: 1
          use-forwarded-headers: "true"
          service:
            loadBalancerIP: 192.168.1.201
            externalTrafficPolicy: Local
          ingressClassResource:
            default: true
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
              namespace: kube-system
            prometheusRule:
              enabled: false

  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true