apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-loki-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: loki-stack
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 0.8.0
    helm:
      releaseName: loki-stack
  destination:
    server: "https://kubernetes.default.svc"
    namespace: loki-stack
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true