apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: 'https://github.com/michalchecinski/k8s-gitops.git'
    path: homepage
    targetRevision: master

  destination:
    server: "https://kubernetes.default.svc"
    namespace: homepage
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true