apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    namespace: n8n
    server: "https://kubernetes.default.svc"
  source:
    repoURL: 'https://github.com/michalchecinski/k8s-gitops.git'
    path: n8n/overlays/main
    targetRevision: master
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true