apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snapshot-validation-webhook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    chart: snapshot-validation-webhook
    repoURL: https://piraeus.io/helm-charts/
    targetRevision: 1.7.1
    helm:
      releaseName: snapshot-validation-webhook
      serviceMonitor:
        create: true

  destination:
    server: "https://kubernetes.default.svc"
    namespace: snapshot
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
