apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: esphome
  name: esphome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esphome
  template:
    metadata:
      labels:
        app: esphome
    spec:
      hostNetwork: true
      containers:
        - image: esphome/esphome:2022.9.4@sha256:907ae118d77c3c63112d7eb09663d6567853df2549e45b9f60fa4803c0aafcdf
          name: esphome
          env:
            - name: ESPHOME_DASHBOARD_USE_PING
              value: "true"
            - name: ESPHOME_DASHBOARD_RELATIVE_URL
              value: "/"
          volumeMounts:
            - mountPath: "/config"
              name: esphome-config
      volumes:
      - name: esphome-config
        persistentVolumeClaim:
          claimName: esphome-config