apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: esphome
  name: esphome
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esphome
  template:
    metadata:
      labels:
        app: esphome
    spec:
      hostNetwork: true
      containers:
        - image: esphome/esphome:1.16.2
          name: esphome
          env:
            - name: ESPHOME_DASHBOARD_USE_PING
              value: "true"
            - name: ESPHOME_DASHBOARD_RELATIVE_URL
              value: "/"
          volumeMounts:
            - mountPath: "/config"
              name: esphome-config
      volumes:
      - name: esphome-config
        persistentVolumeClaim:
          claimName: esphome-config