apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: hass
  name: zigbee2mqtt-backup-b2
spec:
  schedule: "21 01 * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: rclone
            image: rclone/rclone:1.71
            env:
            - name: TZ
              value: "Europe/Warsaw"
            command:
            - "rclone"
            args:
            - "-v"
            - "--config"
            - "/config/rclone.conf"
            - "sync"
            - "--ignore-errors"
            - "--fast-list"
            - "/home"
            - "b2:rclone-k8s-mch-backup/zigbee2mqtt"
            volumeMounts:
            - name: rclone-config
              mountPath: "/config"
            - name: nfs-backup-ro-zigbee2mqtt
              mountPath: /home
          volumes:
          - name: rclone-config
            secret:
              secretName: zigbee2mqtt-backup-rclone-config-secret
          - name: nfs-backup-ro-zigbee2mqtt
            persistentVolumeClaim:
              claimName: zigbee2mqtt-data