apiVersion: v1
kind: ConfigMap
metadata:
  name: zigbee2mqtt-settings
  labels:
    app.kubernetes.io/name: zigbee2mqtt
data:
  configuration.yaml: |
    advanced:
      homeassistant_discovery_topic: homeassistant
      homeassistant_status_topic: homeassistant/status
      last_seen: ISO_8601
      log_level: debug
      log_output:
      - console
      - file
      network_key: GENERATE
    devices: /data/devices.yaml
    experimental:
      new_api: true
    frontend:
      port: 8080
    groups: /data/groups.yaml
    homeassistant: true
    mqtt:
      base_topic: zigbee2mqtt
      include_device_information: true
      server: mqtt://mosquitto.hass
    permit_join: true
    serial:
      port: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_2e8bb2320645ec11b0fc96fd6f14af06-if00-port0
