kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zigbee2mqtt-data
  labels:
    app.kubernetes.io/name: zigbee2mqtt
spec:
  accessModes:
    - "ReadWriteMany"
  storageClassName: longhorn
  resources:
    requests:
      storage: "500Mi"